// <auto-generated />
using System;
using BookIT.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookIT.Persistence.Migrations
{
    [DbContext(typeof(BookItDbContext))]
    [Migration("20260926152737_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookIT.Domain.Entities.Booking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date")
                        .HasColumnName("booking_date");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<int>("EndTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("end_time_minutes");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PublicToken")
                        .HasColumnType("uuid")
                        .HasColumnName("public_token");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id");

                    b.Property<long>("StaffId")
                        .HasColumnType("bigint")
                        .HasColumnName("staff_id");

                    b.Property<int>("StartTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("start_time_minutes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_bookings_customer_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_bookings_organization_id");

                    b.HasIndex("PublicToken")
                        .IsUnique()
                        .HasDatabaseName("ix_bookings_public_token");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_bookings_service_id");

                    b.HasIndex("StaffId", "BookingDate")
                        .HasDatabaseName("ix_bookings_staff_id_booking_date");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("BookIT.Domain.Entities.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_customers_organization_id");

                    b.HasIndex("PhoneNumber", "OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_phone_number_organization_id");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("BookIT.Domain.Entities.Organization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_slug");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("BookIT.Domain.Entities.Service", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_in_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_services_organization_id");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("BookIT.Domain.Entities.Staff", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_number");

                    b.Property<string>("StaffType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("staff_type");

                    b.HasKey("Id")
                        .HasName("pk_staff");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_staff_organization_id");

                    b.HasIndex("PhoneNumber", "OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ix_staff_phone_number_organization_id");

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("BookIT.Domain.Entities.WorkingHour", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ClosingHourMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("closing_hour_minutes");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<int>("OpeningHourMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("opening_hour_minutes");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_working_hours");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_working_hours_organization_id");

                    b.ToTable("working_hours", (string)null);
                });

            modelBuilder.Entity("BookIT.Domain.Entities.Booking", b =>
                {
                    b.HasOne("BookIT.Domain.Entities.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_customers_customer_id");

                    b.HasOne("BookIT.Domain.Entities.Organization", "Organization")
                        .WithMany("Bookings")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_organizations_organization_id");

                    b.HasOne("BookIT.Domain.Entities.Service", "Service")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_services_service_id");

                    b.HasOne("BookIT.Domain.Entities.Staff", "Staff")
                        .WithMany("Bookings")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_staff_staff_id");

                    b.Navigation("Customer");

                    b.Navigation("Organization");

                    b.Navigation("Service");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("BookIT.Domain.Entities.Customer", b =>
                {
                    b.HasOne("BookIT.Domain.Entities.Organization", "Organization")
                        .WithMany("Customers")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customers_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("BookIT.Domain.Entities.Service", b =>
                {
                    b.HasOne("BookIT.Domain.Entities.Organization", "Organization")
                        .WithMany("Services")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_services_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("BookIT.Domain.Entities.Staff", b =>
                {
                    b.HasOne("BookIT.Domain.Entities.Organization", "Organization")
                        .WithMany("Staff")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_staff_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("BookIT.Domain.Entities.WorkingHour", b =>
                {
                    b.HasOne("BookIT.Domain.Entities.Organization", "Organization")
                        .WithMany("WorkingHours")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_working_hours_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("BookIT.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BookIT.Domain.Entities.Organization", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Customers");

                    b.Navigation("Services");

                    b.Navigation("Staff");

                    b.Navigation("WorkingHours");
                });

            modelBuilder.Entity("BookIT.Domain.Entities.Service", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BookIT.Domain.Entities.Staff", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
